---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Home
- type: document
  path: content/_index.md
  label: Hero
  match: "**/*"
- type: document
  path: content/homepage/video.md
  label: Video
  match: "**/*"
- type: document
  path: content/homepage/mission.md
  label: Mission
  match: "**/*"
- type: document
  path: content/services/_index.md
  label: Services Section Title
  match: "**/*"
- type: directory
  path: content/dervices
  label: Services Section Content
  create: documents
  match: "*"
  exclude: _index.md
- type: document
  path: content/comepage/about.md
  label: CTA
  match: "**/*"
- type: heading
  label: Misc
- type: document
  path: config.toml
  label: Configuration
  match: "**/*"
- type: document
  path: data/social.json
  label: Social
upload_dir: assets/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
